title: Alex Cluff # your name (or website title) here
logo: "/images/6546549681.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Statistics Graduate, Ohio State
  <br>
  Statistician, Data Analyst, Data Scientist
  <br><br>
  <a href="mailto: alexcluff16@gmail.com">alexcluff16@gmail.com</a>
  <br>
  (740)-396-9652
  <br><br>
  <a href="https://1drv.ms/w/s!AmjW4WQRYDoyqrt_S09CdJypvW_ozA?e=I9mLcx">View My Resume</a>
  <br><br>
  <a href="https://www.linkedin.com/in/alex-cluff-06b2821b7/">View My LinkedIn Profile</a>

  
theme: jekyll-theme-minimal
google_analytics: UA-157577034-1 # your Google Analytics tracking ID here

