title: Alex Cluff # your name (or website title) here
logo: "/images/6546549681.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Statistics Graduate | Data Analyst/Scientist
  <br>
  B.S. Statistics from Ohio State
  <br><br>
  <a href="mailto: alexcluff16@gmail.com">alexcluff16@gmail.com</a>
  <br>
  (740)-396-9652
  <br><br>
  <iframe src="https://onedrive.live.com/embed?cid=323A601164E1D668&resid=323A601164E1D668%21651998&authkey=AE07PzWjKojQrCk&em=2" width="476" height="288" frameborder="0" scrolling="no"></iframe> 
  <br><br>
  <a href="https://www.linkedin.com/in/alex-cluff-06b2821b7/">View My LinkedIn Profile</a>

  
theme: jekyll-theme-minimal
google_analytics: UA-157577034-1 # your Google Analytics tracking ID here
