title: Alex Cluff # your name (or website title) here
logo: "/images/6546549681.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Recent Graduate of Ohio State
  <br>
  B.S. Statistics
  <br><br>
  I am looking for an entry level position or internship as a Statistician, Data Analyist, or Data Scientist.
  <br><br>
  <a href="https://www.linkedin.com/in/alex-cluff-06b2821b7/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-MQV7JCWZP4 # your Google Analytics tracking ID here
