title: Alex Cluff # your name (or website title) here
logo: "/images/6546549681.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Statistics Graduate | Data Analyst/Scientist
  <br>
  B.S. Statistics from Ohio State
  <br><br>
  <a href="mailto: alexcluff16@gmail.com">alexcluff16@gmail.com</a>
  <br>
  (740)-396-9652
  <br><br>
  <a href="https://kx7kya.dm.files.1drv.com/y4mhnoG8LoGE16H6lk9l94y8AzB-BKABlLRI_7fvfFKr0hWPjFt-ge94w7X5LVIs88h2CMcfujgwZ1bp-eRUQxNkm6l51MjSVuTfg7O5bs_LjuIN1W5iV28R8J6ANForDxveEBCtV_fsarhQQUJxzYe2yT_gMMyEk7fmDMb2DzMZMzH1Ra31NpCNtpSNaN42obu/alex_cluff_resume.pdf?download&psid=1">Download My Resume</a>
  <br><br>
  <a href="https://1drv.ms/b/s!AmjW4WQRYDoyp-VeZYl6xX0DP7ZMaw">View My Resume</a>
  <br><br>
  <a href="https://www.linkedin.com/in/alex-cluff-06b2821b7/">View My LinkedIn Profile</a>

  
theme: jekyll-theme-minimal
google_analytics: UA-157577034-1 # your Google Analytics tracking ID here
