title: Alex Cluff # your name (or website title) here
logo: "/images/6546549681.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Statistics Graduate, Ohio State
  <br>
  Statitican, Data Analyst, Data Scientist
  <br><br>
  <a href="mailto: alexcluff16@gmail.com">alexcluff16@gmail.com</a>
  <br>
  (740)-396-9652
  <br><br>
  <a href="https://onedrive.live.com/embed?cid=323A601164E1D668&amp;resid=323A601164E1D668%21695807&amp;authkey=AL5T6Z68bI0VLV4&amp;em=2">View My Resume</a>
  <br><br>
  <a href="https://www.linkedin.com/in/alex-cluff-06b2821b7/">View My LinkedIn Profile</a>

  
theme: jekyll-theme-minimal
google_analytics: UA-157577034-1 # your Google Analytics tracking ID here

